wip(ci): Use crates.io release of z3.rs
We can set Z3_SYS_BUNDLED_DIR_OVERRIDE to point to a local instance of
the Z3 source code, which should allow CI runners to compile Z3 from
source while also allowing us to use the crates.io version of z3

diff --git a/.github/workflows/python_ci.yaml b/.github/workflows/python_ci.yaml
--- a/.github/workflows/python_ci.yaml
+++ b/.github/workflows/python_ci.yaml
@@ -24,9 +24,11 @@ jobs:
       matrix:
         os: [ubuntu-latest, ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-15-intel, macos-latest]
 
-
-    # TODO: Clean this up
     env:
+      MATURIN_PEP517_ARGS: "--features=default,pyo3/extension-module,z3_bundled -vvv"
+      MACOSX_DEPLOYMENT_TARGET: "10.12"
+      Z3_SYS_BUNDLED_DIR_OVERRIDE: "./z3_git_source"
+
       CIBW_BEFORE_ALL_LINUX: |
         if command -v apk &> /dev/null; then
           apk add --no-cache build-base clang llvm-dev clang-dev curl bash
@@ -37,11 +39,14 @@ jobs:
         elif command -v dnf &> /dev/null; then
           dnf groupinstall -y 'Development Tools' && dnf install -y clang llvm-devel clang-devel curl
         else
-          echo "No supported package manager found"
+          echo "Error: No supported package manager found" >&2
+          exit 1
         fi
+
         curl -sSf https://sh.rustup.rs | sh -s -- -y
-      CIBW_ENVIRONMENT_LINUX: "PATH=$HOME/.cargo/bin:$PATH MATURIN_PEP517_ARGS='--features=default,pyo3/extension-module,z3_bundled -vvv' MACOSX_DEPLOYMENT_TARGET=10.12"
-      CIBW_ENVIRONMENT: "MATURIN_PEP517_ARGS='--features=default,pyo3/extension-module,z3_bundled -vvv' MACOSX_DEPLOYMENT_TARGET=10.12"
+
+      CIBW_ENVIRONMENT_LINUX: "PATH=$HOME/.cargo/bin:$PATH"
+
       CIBW_BEFORE_ALL_WINDOWS: "rustup target add i686-pc-windows-msvc"
 
     steps:
@@ -51,6 +56,13 @@ jobs:
         uses: actions/setup-python@v6
         with:
           python-version: '3.13'
+
+      - name: Clone Z3
+        uses: actions/checkout@v5
+        with:
+          repository: Z3Prover/z3
+          path: ./z3_git_source
+          ref: z3-4.15.3
 
       - name: Install cibuildwheel
         run: python -m pip install cibuildwheel==3.2.0
